#pragma once
// Generated by build script, do not edit!
#define UNITY_VERSION_FULL "2019.3.14f1_2b330bf6d2d8"
#define UNITY_VERSION_FULL_NICE "2019.3.14f1 (2b330bf6d2d8)"
#define UNITY_VERSION_BLD 2831115
#define UNITY_VERSION_DATE 1589291438
#define UNITY_VERSION_WIN "2019.3.14.2831115"
#define UNITY_VERSION_BRANCH "2019.3/release"
